%
% Chromatic aberration computations as shown in Wandell (1995) and
% in Marimont & Wandell (1993).
%

% First, generate OTF, optical transfer function by wavelengths,
% which reflects blurring caused by chromatic aberration of the lens
% of the human eye.
%
% OTF is generated by a C program called otf. It prompts you for parameters
% such as pupil radius, min wavelength, max wavelength, etc.
%
% An example OTF was generated and stored in otf.mat. Its parameters were:
% 1-dimensional,
% wavelength range 390-730nm,
% frequency range 0-32 cpd,
% pupil radius 2.75mm.
