% Experimenting with Matlab's image registration features

img1 = imread('BanteaySrei_01.jpg');
img2 = imread('BanteaySrei_02.jpg');

%registrationEstimator(rgb2gray(img1), rgb2gray(img2));

%[optimizer, metric] = imregconfig('monomodal');
%imgTForm = imregtform(rgb2gray(img1),rgb2gray(img2),'affine',...
%    optimizer,metric);

merge = registerImages(rgb2gray(img2), rgb2gray(img1));
imshowpair(img2, (imwarp(img1, merge.Transformation)), 'diff');


function [MOVINGREG] = registerImages(MOVING, FIXED)
%registerImages  Register grayscale images using auto-generated code from Registration Estimator app.
%  [MOVINGREG] = registerImages(MOVING,FIXED) Register grayscale images
%  MOVING and FIXED using auto-generated code from the Registration
%  Estimator app. The values for all registration parameters were set
%  interactively in the app and result in the registered image stored in the
%  structure array MOVINGREG.

% Auto-generated by registrationEstimator app on 27-Jan-2021
%-----------------------------------------------------------


% Feature-based techniques require license to Computer Vision Toolbox
checkLicense()

% Default spatial referencing objects
fixedRefObj = imref2d(size(FIXED));
movingRefObj = imref2d(size(MOVING));

% Detect SURF features
fixedPoints = detectSURFFeatures(FIXED, 'MetricThreshold', 750.000000, 'NumOctaves', 3, 'NumScaleLevels', 5);
movingPoints = detectSURFFeatures(MOVING, 'MetricThreshold', 750.000000, 'NumOctaves', 3, 'NumScaleLevels', 5);

% Extract features
[fixedFeatures, fixedValidPoints] = extractFeatures(FIXED, fixedPoints, 'Upright', false);
[movingFeatures, movingValidPoints] = extractFeatures(MOVING, movingPoints, 'Upright', false);

% Match features
indexPairs = matchFeatures(fixedFeatures, movingFeatures, 'MatchThreshold', 50.000000, 'MaxRatio', 0.500000);
fixedMatchedPoints = fixedValidPoints(indexPairs(:, 1));
movingMatchedPoints = movingValidPoints(indexPairs(:, 2));
MOVINGREG.FixedMatchedFeatures = fixedMatchedPoints;
MOVINGREG.MovingMatchedFeatures = movingMatchedPoints;

% Apply transformation - Results may not be identical between runs because of the randomized nature of the algorithm
tform = estimateGeometricTransform(movingMatchedPoints, fixedMatchedPoints, 'projective');
MOVINGREG.Transformation = tform;
MOVINGREG.RegisteredImage = imwarp(MOVING, movingRefObj, tform, 'OutputView', fixedRefObj, 'SmoothEdges', true);

% Store spatial referencing object
MOVINGREG.SpatialRefObj = fixedRefObj;

end

function checkLicense()

% Check for license to Computer Vision Toolbox
CVSTStatus = license('test', 'Video_and_Image_Blockset');
if ~CVSTStatus
    error(message('images:imageRegistration:CVSTRequired'));
end

end
